# Generated by Django 5.2.3 on 2025-06-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('media', models.FileField(upload_to='')),
            ],
        ),
    ]
