# Generated by Django 5.2.3 on 2025-06-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
