# Generated by Django 5.2.3 on 2025-07-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='image',
            field=models.ImageField(null=True, upload_to='reference_imgs/'),
        ),
    ]
