# Generated by Django 5.2.3 on 2025-07-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(null=True, upload_to='reference/'),
        ),
    ]
